version: "3.8"
services:
  mqtt:
    image: "eclipse-mosquitto"
    volumes:
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
    networks:
      - dummylink

  mqtt-panel:
    image: sourcesimian/mqtt-panel
    depends_on:
      - mqtt
    volumes:
      - ./conf/mqtt-panel.yaml:/config.yaml
      - ./cache/mqtt-panel:/data/cache
    ports:
      - 8888:8080
    networks:
      - dummylink

  frequency-api:
    build: ./frequency-api/
    depends_on:
      - mqtt
    ports:
      - 3000:3000
    networks:
      - dummylink

  device1:
    build: ./traffic-generator/
    depends_on:
      - mqtt
    environment:
      - BROKER_URL=mqtt
      - BROKER_PORT=1883
      - DEVICE_NAME=device1
      - STATE_FILE_PATH=/opt/device/state
    networks:
      - dummylink
    command: python /opt/device/src/simulation.py 1 
  device2:
    build: ./traffic-generator/
    depends_on:
      - mqtt
    environment:
      - BROKER_URL=mqtt
      - BROKER_PORT=1883
      - DEVICE_NAME=device2
      - STATE_FILE_PATH=/opt/device/state
    networks:
      - dummylink
    command: python /opt/device/src/simulation.py 2


  device3:
    build: ./traffic-generator/
    depends_on:
      - mqtt
    environment:
      - BROKER_URL=mqtt
      - BROKER_PORT=1883
      - DEVICE_NAME=device3
      - STATE_FILE_PATH=/opt/device/state
    networks:
      - dummylink
    command: python /opt/device/src/simulation.py 3
  device4:
    build: ./traffic-generator/
    depends_on:
      - mqtt
    environment:
      - BROKER_URL=mqtt
      - BROKER_PORT=1883
      - DEVICE_NAME=device4
      - STATE_FILE_PATH=/opt/device/state
    networks:
      - dummylink
    command: python /opt/device/src/simulation.py 4
  device5:
    build: ./traffic-generator/
    depends_on:
      - mqtt
    environment:
      - BROKER_URL=mqtt
      - BROKER_PORT=1883
      - DEVICE_NAME=device5
      - STATE_FILE_PATH=/opt/device/state
    networks:
      - dummylink
    command: python /opt/device/src/simulation.py 5
  your-microservice:  
    build:
      context: ./your-microservice
      dockerfile: Dockerfile
    depends_on:
      - mqtt
      - frequency-api 
    environment:
      - MQTT_BROKER=mqtt://mqtt:1883  
      - API_BASE_URL=http://frequency-api:3000 
    networks:
      - dummylink 

networks:
  dummylink: {}