version: "3.9"

services:
  mqtt:
    image: "eclipse-mosquitto"
    volumes:
      - $PWD/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
    networks:
      - dummylink

  device_1:
    build: ./traffic-generator/
    depends_on:
      - mqtt
    environment:
      - BROKER_URL=mqtt
      - BROKER_PORT=1883
      - DEVICE_NAME=device1
    networks:
      - dummylink

  device_2:
    build: ./traffic-generator/
    depends_on:
      - mqtt
    environment:
      - BROKER_URL=mqtt
      - BROKER_PORT=1883
      - DEVICE_NAME=device2
    networks:
      - dummylink

  device_3:
    build: ./traffic-generator/
    depends_on:
      - mqtt
    environment:
      - BROKER_URL=mqtt
      - BROKER_PORT=1883
      - DEVICE_NAME=device3
    networks:
      - dummylink


networks:
  dummylink: